export type Locale = "tr" | "en";

const tr = {
  "common.backToChat": "Sohbete dön",
  "common.chat": "Sohbet",
  "common.excel": "Excel",
  "common.loading": "Yükleniyor…",
  "common.course": "Ders",
  "common.courses": "Dersler",
  "common.saved": "Kaydedildi",
  "common.remove": "Kaldır",
  "common.clear": "Temizle",
  "common.admin": "Yönetici",
  "common.student": "Öğrenci",
  "common.cancel": "Vazgeç",
  "common.section": "Section",
  "common.dataSheet": "Veri",
  "common.unknownCourseTitle": "Ders adı",
  "theme.title": "Tema: {preference}",
  "theme.change": "Temayı değiştir",
  "language.change": "Switch to English",
  "language.short": "EN",
  "login.tagline1": "Kalan derslerini gör.",
  "login.tagline2": "Seçmelileri ve yan dalları kontrol et.",
  "login.tagline3": "Resmî müfredat verilerinden yanıt al.",
  "login.studentsAsk": "Öğrenciler soruyor",
  "login.title": "Tekrar hoş geldin",
  "login.subtitle": "adviSU'ya devam etmek için giriş yap.",
  "login.username": "Kullanıcı adı",
  "login.password": "Şifre",
  "login.hidePassword": "Şifreyi gizle",
  "login.showPassword": "Şifreyi göster",
  "login.signingIn": "Giriş yapılıyor…",
  "login.signIn": "Giriş yap",
  "login.missing": "Kullanıcı adı ve şifreyi gir.",
  "login.invalid": "Bilgiler geçersiz. Demo için admin / admin kullanabilirsin.",
  "login.studentDemo": "Öğrenci demosu",
  "login.policy": "Ders değerlendirme veri politikası",
  "login.logoAlt": "adviSU — Sabancı Üniversitesi Akademik Danışmanı",
  "login.askLabel": "Öğrenciler şunları soruyor",
  "login.eyebrow": "Mezuniyet analizi · 9 program · 4 müfredat yılı",
  "login.headlineTop": "Ne kaldığını",
  "login.headlineBottom": "tam olarak gör.",
  "login.lede": "adviSU ders geçmişini, programının ve giriş döneminin resmî müfredatıyla karşılaştırır — kategori kategori, kredi kredi.",
  "login.welcome": "Tekrar hoş geldin",
  "login.missingFields": "Kullanıcı adı ve parolanı gir.",
  "login.passwordHint": "Parolanı gir",
  "login.submit": "Giriş yap",
  "login.submitting": "Giriş yapılıyor…",
  "login.demoHeading": "Demo hesapları",
  "login.demoAccounts": "Öğrenci demo",
  "login.adminAccount": "Yönetici",
  "login.footer": "adviSU · CS 455 dönem projesi · Sabancı Üniversitesi",
  "signup.description": "Resmî Sabancı Üniversitesi müfredat verileriyle çalışan akademik danışmanlık sistemi.",
  "signup.title": "Hesap oluştur",
  "signup.subtitle": "Birkaç saniyede adviSU'ya katıl",
  "signup.fullName": "Ad Soyad",
  "signup.email": "E-posta",
  "signup.password": "Şifre",
  "signup.agree": "Koşulları ve Gizlilik Politikasını kabul ediyorum",
  "signup.submit": "Kaydol",
  "signup.haveAccount": "Zaten hesabın var mı?",
  "signup.login": "Giriş yap",
  "signup.missing": "Tüm alanları doldur.",
  "signup.mustAgree": "Devam etmek için koşulları ve gizlilik politikasını kabul etmelisin.",
  "signup.disabled": "Kayıt açık değil. Lütfen yöneticinin sağladığı hesabı kullan.",
  "chat.header": "Akademik danışman",
  "chat.subtitle": "Resmî Sabancı müfredatı ve kişisel ders geçmişinle yanıtlar",
  "chat.openHistory": "Sohbet geçmişini aç",
  "chat.profileNotice": "Kişisel mezuniyet hesabı için bölümünü ve müfredat dönemini kaydet.",
  "chat.openProfile": "Profili aç",
  "chat.placeholder": "Mezuniyetini sor veya “CS 201’i aldım” yaz…",
  "chat.attachTranscript": "Transkript ekle (PDF)",
  "chat.transcriptProcessing": "Transkriptini işliyorum…",
  "chat.transcriptAttached": "📎 {filename} eklendi",
  "chat.transcriptProcessed": "Transkriptinizdeki dersleri işledim: {count} ders eklendi/güncellendi, GPA {gpa}.",
  "chat.transcriptProcessedUnmatched": " Katalogda bulunamayan dersler: {codes}.",
  "chat.transcriptChatFailed": "Transkripti işleyemedim: {message}",
  "chat.send": "Gönder",
  "chat.thinking": "adviSU düşünüyor…",
  "chat.writing": "Yanıt yazılıyor",
  "chat.sources": "Teknik kaynaklar ({count})",
  "chat.scheduleOpen": "Ders Programına Git",
  "chat.copied": "Kopyalandı",
  "chat.copyCrns": "CRN'leri kopyala",
  "chat.scheduleSaved": "Yeni ders programın kaydedildi.",
  "chat.scheduleSavedDescription": "Ders Programı sayfasında inceleyebilir ve düzenleyebilirsin.",
  "chat.goSchedule": "Programa git",
  "chat.scheduleOffline": "Program bu cihazda güvende; hesabına senkronize edilemedi.",
  "chat.requestFailed": "İstek başarısız oldu",
  "chat.backendError": "Üzgünüm — sunucu bir hata döndürdü: {message}",
  "errors.http": "İstek başarısız oldu (HTTP {status}).",
  "chat.openFailed": "Bu sohbet açılamadı.",
  "chat.deleteFailed": "Bu sohbet silinemedi.",
  "chat.renameFailed": "Sohbet yeniden adlandırılamadı.",
  "chat.pinFailed": "Sabitleme değiştirilemedi.",
  "chat.greeting": "Merhaba{suffix}",
  "chat.help": "Mezuniyet yolculuğunda bugün sana nasıl yardımcı olabilirim?",
  "usage.tooltip": "Günlük {limit} model destekli soru hakkı; doğrulanmış yerel işlemler ve reddedilen istekler sayılmaz.",
  "usage.none": "Bugünkü model hakkın bitti",
  "usage.remaining": "{remaining}/{limit} model sorusu kaldı",
  "usage.label": "Günlük limit",
  "sidebar.schedule": "Ders programı",
  "sidebar.newChat": "Yeni sohbet",
  "sidebar.closeMenu": "Menüyü kapat",
  "sidebar.hideHistory": "Sohbet geçmişini gizle",
  "sidebar.history": "Sohbet geçmişi",
  "sidebar.empty": "İlk sorundan sonra sohbetlerin burada görünecek.",
  "sidebar.unpin": "Sabitlemeyi kaldır",
  "sidebar.pin": "Sohbeti sabitle",
  "sidebar.rename": "Sohbeti yeniden adlandır",
  "sidebar.delete": "Sohbeti sil",
  "sidebar.courseHistory": "Ders geçmişi",
  "sidebar.profile": "Profil ve mezuniyet",
  "sidebar.signOut": "Çıkış yap",
  "sidebar.resize": "Kenar çubuğunu yeniden boyutlandır",
  "sidebar.resizeTitle": "Sürükle veya odaklanıp ok tuşlarını kullan",
  "sidebar.deleteConfirmTitle": "Sohbeti sil",
  "sidebar.deleteConfirmBody": "“{title}” kalıcı olarak silinecek. Bu işlem geri alınamaz.",
  "time.now": "şimdi",
  "time.minute": "{count} dk",
  "time.hour": "{count} sa",
  "time.day": "{count} gün",
  "profile.title": "Akademik Profil ve Mezuniyet Denetimi",
  "profile.eyebrow": "Profilin",
  "profile.heroTitle": "Bölümünü ve müfredat dönemini kaydet",
  "profile.heroBody": "Mezuniyet denetimi yalnızca kaydettiğin program ve dönemin resmî şartlarını kullanır — doğru sonuç için ikisi de gerekli.",
  "profile.curriculum": "Müfredatın",
  "profile.major": "Bölüm (program)",
  "profile.selectMajor": "Bölüm seç…",
  "profile.term": "Müfredat (kabul) dönemi",
  "profile.selectTerm": "Müfredat dönemi seç…",
  "profile.degreeCode": "Program kodu: {code}",
  "profile.year": "Mevcut akademik yıl",
  "profile.yearUnknown": "Belirtilmedi (temkinli planlama kullan)",
  "profile.save": "Profili kaydet",
  "profile.saved": "Profil kaydedildi.",
  "profile.pickFirst": "Önce bölümünü ve müfredat dönemini seç.",
  "profile.loadFailed": "Müfredatlar yüklenemedi.",
  "profile.saveFailed": "Kaydetme başarısız oldu.",
  "profile.contract": "Müfredat dönemin mezuniyet sözleşmendir; denetim yalnızca bu program ve dönemin resmî şartlarını kullanır.",
  "profile.audit": "Mezuniyet denetimi",
  "profile.runAudit": "Denetimi çalıştır",
  "profile.auditFailed": "Denetim başarısız oldu — önce profilini kaydet.",
  "profile.auditHelpBefore": "Profilini kaydet,",
  "profile.auditHelpLink": "Ders Geçmişi",
  "profile.auditHelpAfter": "sayfasında tamamladığın dersleri ekle ve denetimi çalıştır.",
  "profile.suCredits": "/ {total} SU kredisi",
  "profile.category": "Kategori",
  "profile.done": "Tamamlanan",
  "profile.need": "Gerekli",
  "profile.remaining": "Kalan",
  "profile.left": "{count} kaldı",
  "profile.missing": "Eksik zorunlu:",
  "profile.reliability": "Güvenilirlik: {value} · resmî şartlardan deterministik hesaplandı.",
  "courses.title": "Ders Geçmişi",
  "courses.eyebrow": "Ders geçmişin",
  "courses.heroTitle": "Tamamladığın dersleri işaretle",
  "courses.heroBody": "Transkriptini yükle, otomatik eklensin — ya da katalogdan ara.",
  "courses.completed": "Tamamlanan dersler",
  "courses.savedCount": "{count} kayıtlı",
  "courses.emptyTitle": "Henüz ders eklenmedi",
  "courses.empty": "Katalogda ara, tamamladığın dersleri seç ve kaydet; burada listelenip mezuniyet denetiminde kullanılacaklar.",
  "courses.countNote": "Yalnızca tamamlanan dersler mezuniyete sayılır. Mezuniyet denetimi bu listeyi okur.",
  "courses.gpa": "GPA",
  "courses.transcriptTitle": "Transkriptten aktar",
  "courses.transcriptBrowse": "Transkript PDF'i seç",
  "courses.transcriptParsing": "Transkript işleniyor…",
  "courses.transcriptImported": "{count} ders transkriptten işlendi. GPA: {gpa}",
  "courses.transcriptUnmatched": "Katalogda bulunamayan dersler: {codes}",
  "courses.transcriptFailed": "Transkript işlenemedi.",
  "courses.grade": "Not",
  "courses.gradeNone": "Not yok",
  "courses.clearAll": "Tümünü temizle",
  "courses.clearAllConfirmTitle": "Tüm dersleri temizle?",
  "courses.clearAllConfirmBody": "Kayıtlı {count} ders bu listeden kaldırılacak. Bu işlem geri alınamaz.",
  "courses.clearAllConfirmAction": "Evet, temizle",
  "courses.removeCourse": "Dersi kaldır",
  "courses.add": "Ders ekle",
  "courses.search": "CS 300, MATH 101 ara…",
  "courses.loading": "Dersler yükleniyor",
  "courses.none": "Ders bulunamadı",
  "courses.saveCount": "{count} dersi kaydet",
  "courses.catalogFailed": "Ders kataloğu yüklenemedi.",
  "courses.historyFailed": "Kayıtlı ders geçmişin yüklenemedi.",
  "courses.savedToast": "{count} tamamlanmış ders kaydedildi.",
  "courses.saveFailed": "Ders geçmişin kaydedilemedi.",
  "courses.documents": "Ders belgeleri",
  "courses.browse": "Dosya seçmek için tıkla",
  "courses.removeFile": "Dosyayı kaldır",
  "courses.indexing": "İndeksleniyor…",
  "courses.upload": "adviSU'ya yükle",
  "courses.uploaded": "{files} dosya yüklendi — {chunks} parça indekslendi",
  "courses.skipped": "Atlandı: {files}",
  "courses.uploadFailed": "Yükleme başarısız oldu.",
  "schedule.title": "Ders Programı",
  "schedule.reference": "SUchedule (aburakayaz) referans alınarak tasarlandı",
  "schedule.term": "dönem {term}",
  "schedule.pick": "Ders ve section seç",
  "schedule.officialSuffix": "resmî SUIS verisi",
  "schedule.seasonFall": "Güz",
  "schedule.seasonSpring": "Bahar",
  "schedule.seasonSummer": "Yaz",
  "schedule.courseCount": "{count} ders",
  "schedule.search": "Ders kodu, adı, hoca adı veya CRN ara",
  "schedule.clearSearch": "Aramayı temizle",
  "schedule.filterDay": "Güne göre filtrele",
  "schedule.byDay": "Güne göre",
  "schedule.loading": "Dersler yükleniyor",
  "schedule.loadFailed": "Ders listesine ulaşılamadı.",
  "schedule.localSafe": "Mevcut programın cihazında güvende.",
  "schedule.noResults": "Arama veya gün filtresine uygun ders bulunamadı.",
  "schedule.selected": "{count} seçili",
  "schedule.alreadySelected": "Bu section zaten programında.",
  "schedule.moreHint": "Daha net sonuçlar için ders kodu veya CRN yaz.",
  "schedule.week": "Haftalık görünüm",
  "schedule.weekHint": "Derse tıkla ve soldan section değiştir; × ile bağlı bileşenleri birlikte kaldır.",
  "schedule.downloadExcel": "Excel indir",
  "schedule.removeBundle": "{course} ve bağlı section'ları kaldır",
  "schedule.time": "Saat",
  "schedule.conflicting": "Çakışıyor",
  "schedule.conflicts": "{count} çakışma",
  "schedule.emptyTitle": "Programını oluşturmaya başla",
  "schedule.emptyBody": "Soldan ders ve section seç veya chatbot'tan hazırlanan programı buraya aktar.",
  "schedule.noClass": "Ders yok",
  "schedule.saving": "Kaydediliyor",
  "schedule.offline": "Bu cihazda kayıtlı",
  "schedule.noTime": "Saat açıklanmadı",
  "schedule.sectionLoadFailed": "{course} section seçenekleri yüklenemedi.",
  "schedule.primaryUpdated": "{course} ders section'ı güncellendi.",
  "schedule.incompatibleRemoved": "{course} güncellendi; uyumsuz bağlı section kaldırıldı.",
  "schedule.added": "{course} programa eklendi.",
  "schedule.bundleAdded": "{course} dersi ve bağlı {component} birlikte eklendi.",
  "schedule.secondaryUpdated": "{course} {component} section'ı güncellendi.",
  "schedule.bundleRemoved": "{course} ve bağlı section'ları birlikte kaldırıldı.",
  "schedule.removed": "{course} programdan kaldırıldı.",
  "schedule.copyFailed": "CRN'ler panoya kopyalanamadı.",
  "schedule.clearConfirmTitle": "Programı temizle",
  "schedule.clearConfirm": "Programındaki tüm dersleri kaldırmak istediğine emin misin? Bu işlem geri alınamaz.",
  "schedule.cleared": "Ders programı temizlendi.",
  "schedule.dayMon": "Pazartesi",
  "schedule.dayTue": "Salı",
  "schedule.dayWed": "Çarşamba",
  "schedule.dayThu": "Perşembe",
  "schedule.dayFri": "Cuma",
  "schedule.dayMonShort": "Pzt",
  "schedule.dayTueShort": "Sal",
  "schedule.dayWedShort": "Çar",
  "schedule.dayThuShort": "Per",
  "schedule.dayFriShort": "Cum",
  "schedule.defaultTerm": "Güz 2026-2027",
  "schedule.defaultComponent": "Ders",
  "policy.title": "Ders değerlendirme veri politikası",
  "policy.status": "Bu özellik şu anda devre dışıdır.",
  "policy.body": "Yayınlanırsa yalnızca dersleri değerlendirir; profesör veya öğretim üyesini değil.",
  "policy.point1": "Her gönderim için açık onay gerekir.",
  "policy.point2": "Özel WhatsApp ve ders grubu mesajları hiçbir zaman içe aktarılmaz.",
  "policy.point3": "Yalnızca zorluk, iş yükü, öğrenme değeri, düzen ve genel memnuniyet puanlanır.",
  "policy.point4": "Yorumlar moderasyondan geçer; kişi ve öğretim üyesi adları filtrelenir.",
  "policy.point5": "En az 10 onaylı değerlendirme olmadan istatistik gösterilmez.",
  "policy.point6": "Küçük alt gruplar ve ham kimlikler hiçbir zaman gösterilmez.",
  "policy.back": "Girişe dön",
  "review.title": "Dersini değerlendir",
  "review.courseCode": "Ders kodu",
  "review.courseCodePlaceholder": "CS 201",
  "review.difficulty": "Zorluk",
  "review.workload": "İş yükü",
  "review.learningValue": "Öğrenme değeri",
  "review.organization": "Düzen",
  "review.satisfaction": "Genel memnuniyet",
  "review.scoreLabel": "{dimension}: {score} / 5",
  "review.comment": "Ders hakkında yorum (isteğe bağlı, moderasyon gerekir)",
  "review.commentPlaceholder": "Kişi adı veya iletişim bilgisi yazma.",
  "review.consent": "Puanlarımın ders düzeyinde ve gizlilik eşiğiyle işlenmesine açıkça onay veriyorum.",
  "review.courseOnly": "Bu form yalnızca dersi değerlendirir; öğretim üyesi veya kişi puanlanamaz.",
  "review.privacyLink": "Gizlilik politikasını oku",
  "review.submit": "Değerlendirmeyi gönder",
  "review.submitting": "Gönderiliyor…",
  "review.signIn": "Değerlendirme göndermek için giriş yap.",
  "review.loadError": "Ders değerlendirme politikası yüklenemedi.",
  "review.submitError": "Değerlendirme gönderilemedi.",
  "review.pending": "Değerlendirmen moderasyon bekliyor.",
  "review.approved": "Sayısal değerlendirmen kabul edildi.",
  "review.rejected": "Değerlendirme gizlilik politikasına uygun bulunmadı.",
  "review.aggregateTitle": "Ders istatistikleri",
  "review.aggregateLoading": "İstatistikler yükleniyor…",
  "review.aggregateSuppressed": "En az 10 onaylı değerlendirme olmadan istatistik gösterilmez.",
  "review.aggregateError": "İstatistikler yüklenemedi.",
  "review.reviewCount": "{count} onaylı değerlendirme",
  "review.delete": "Değerlendirmemi sil",
  "review.deleting": "Siliniyor…",
  "review.deleted": "Değerlendirmen silindi.",
  "review.deleteError": "Değerlendirme silinemedi.",
  "export.courseCode": "Ders Kodu",
  "export.courseName": "Ders Adı",
  "export.su": "SU Kredisi",
  "export.status": "Durum",
  "export.total": "TOPLAM (kredi sayan)",
  "export.courseHistorySheet": "Ders Geçmişi",
  "export.field": "Alan",
  "export.value": "Değer",
  "export.program": "Program",
  "export.curriculumTerm": "Müfredat dönemi",
  "export.completedSu": "Tamamlanan SU",
  "export.requiredSu": "Gerekli SU",
  "export.remainingSu": "Kalan SU",
  "export.reliability": "Güvenilirlik",
  "export.summarySheet": "Özet",
  "export.categoriesSheet": "Kategoriler",
  "export.missingCourse": "Eksik Zorunlu Ders",
  "export.missingSheet": "Eksik Zorunlu",
  "export.type": "Tür",
  "export.dayTime": "Gün / Saat",
  "export.location": "Yer",
  "export.instructor": "Öğretim Üyesi",
  "export.term": "Dönem",
  "export.completedEcts": "Tamamlanan ECTS",
  "export.requiredEcts": "Gerekli ECTS",
  "export.remainingEcts": "Kalan ECTS",
  "export.weekSheet": "Haftalık Program",
  "help.button": "Yardım",
  "help.title": "adviSU nasıl çalışır?",
  "help.tip1": "Sorularını doğal dilde sor — “CS 306 zorunlu mu?” gibi.",
  "help.tip2": "Kişisel mezuniyet hesabı için Profil'de bölümünü ve müfredat dönemini kaydet.",
  "help.tip3": "Tamamladığın dersleri Ders Geçmişi'nde işaretle; denetim bu listeyi okur.",
  "help.tip4": "Ders Programı sayfasında section seç, çakışmalar otomatik işaretlenir.",
  "help.close": "Kapat",
} as const;

const en: Record<keyof typeof tr, string> = {
  ...tr,
  "common.backToChat": "Back to chat", "common.chat": "Chat", "common.loading": "Loading…",
  "common.course": "Course", "common.courses": "Courses", "common.saved": "Saved",
  "common.remove": "Remove", "common.clear": "Clear", "common.admin": "Administrator",
  "common.student": "Student", "common.section": "Section", "common.dataSheet": "Data",
  "common.cancel": "Cancel",
  "common.unknownCourseTitle": "Course title",
  "theme.title": "Theme: {preference}", "theme.change": "Change theme",
  "language.change": "Türkçeye geç", "language.short": "TR",
  "login.tagline1": "See what you have left.", "login.tagline2": "Check electives and minors.",
  "login.tagline3": "Answers from official curriculum data.", "login.studentsAsk": "Students ask",
  "login.title": "Welcome back", "login.subtitle": "Sign in to continue to adviSU.",
  "login.username": "Username", "login.password": "Password", "login.hidePassword": "Hide password",
  "login.showPassword": "Show password", "login.signingIn": "Signing in…", "login.signIn": "Sign in",
  "login.missing": "Please enter both a username and a password.",
  "login.invalid": "Invalid credentials. Use admin / admin for this demo.",
  "login.studentDemo": "Student demo", "login.policy": "Course review data policy",
  "login.logoAlt": "adviSU — Sabancı University Academic Advisor",
  "login.askLabel": "Students are asking",
  "login.eyebrow": "Degree analysis · 9 programs · 4 curriculum years",
  "login.headlineTop": "See exactly",
  "login.headlineBottom": "what remains.",
  "login.lede": "adviSU compares your course history with the official curriculum for your program and admission term — category by category, credit by credit.",
  "login.welcome": "Welcome back",
  "login.missingFields": "Enter your username and password.",
  "login.passwordHint": "Enter your password",
  "login.submit": "Sign in",
  "login.submitting": "Signing in…",
  "login.demoHeading": "Demo accounts",
  "login.demoAccounts": "Student demo",
  "login.adminAccount": "Administrator",
  "login.footer": "adviSU · CS 455 term project · Sabancı University",
  "signup.description": "Academic advising powered by official Sabancı University curriculum data.",
  "signup.title": "Create an account", "signup.subtitle": "Join adviSU in a few seconds",
  "signup.fullName": "Full Name", "signup.email": "Email", "signup.password": "Password",
  "signup.agree": "I agree to the Terms & Privacy", "signup.submit": "Sign Up",
  "signup.haveAccount": "Already have an account?", "signup.login": "Log in",
  "signup.missing": "Please fill in all fields.",
  "signup.mustAgree": "You must accept the Terms & Privacy to continue.",
  "signup.disabled": "Registration is not enabled. Please use an account provided by the administrator.",
  "chat.header": "Academic advisor", "chat.subtitle": "Answers from official Sabancı curricula and your course history",
  "chat.openHistory": "Open chat history", "chat.profileNotice": "Save your major and curriculum term for a personalized degree audit.",
  "chat.openProfile": "Open profile", "chat.placeholder": "Ask about graduation or write “I completed CS 201”…",
  "chat.attachTranscript": "Attach transcript (PDF)",
  "chat.transcriptProcessing": "Processing your transcript…",
  "chat.transcriptAttached": "📎 {filename} attached",
  "chat.transcriptProcessed": "I've processed the courses from your transcript: {count} courses added/updated, GPA {gpa}.",
  "chat.transcriptProcessedUnmatched": " Courses not found in the catalog: {codes}.",
  "chat.transcriptChatFailed": "I couldn't process this transcript: {message}",
  "chat.send": "Send", "chat.thinking": "adviSU is thinking…", "chat.writing": "Response is being written",
  "chat.sources": "Technical sources ({count})", "chat.scheduleOpen": "Open Course Schedule",
  "chat.copied": "Copied", "chat.copyCrns": "Copy CRNs", "chat.scheduleSaved": "Your new course schedule was saved.",
  "chat.scheduleSavedDescription": "Review and edit it on the Course Schedule page.", "chat.goSchedule": "Open schedule",
  "chat.scheduleOffline": "The schedule is safe on this device but could not sync to your account.",
  "chat.requestFailed": "Request failed", "chat.backendError": "Sorry — the backend returned an error: {message}",
  "errors.http": "Request failed (HTTP {status}).",
  "chat.openFailed": "Could not open that conversation.", "chat.deleteFailed": "Could not delete that conversation.",
  "chat.renameFailed": "Could not rename that conversation.", "chat.pinFailed": "Could not change the pin.",
  "chat.greeting": "Hello{suffix}", "chat.help": "How can I help with your graduation journey today?",
  "usage.tooltip": "Daily allowance of {limit} provider-backed questions; verified local operations and refused requests do not count.",
  "usage.none": "No model-backed questions left today",
  "usage.remaining": "{remaining}/{limit} model questions left",
  "usage.label": "Daily limit",
  "sidebar.schedule": "Course schedule", "sidebar.newChat": "New chat", "sidebar.closeMenu": "Close menu",
  "sidebar.hideHistory": "Hide chat history", "sidebar.history": "Chat history",
  "sidebar.empty": "Your conversations will appear here after your first question.",
  "sidebar.unpin": "Unpin conversation", "sidebar.pin": "Pin conversation", "sidebar.rename": "Rename conversation",
  "sidebar.delete": "Delete conversation", "sidebar.courseHistory": "Course history",
  "sidebar.profile": "Profile and degree audit", "sidebar.signOut": "Sign out",
  "sidebar.resize": "Resize sidebar", "sidebar.resizeTitle": "Drag, or focus and use arrow keys",
  "sidebar.deleteConfirmTitle": "Delete conversation",
  "sidebar.deleteConfirmBody": "“{title}” will be permanently deleted. This cannot be undone.",
  "time.now": "now", "time.minute": "{count} min", "time.hour": "{count} hr", "time.day": "{count} day",
  "profile.title": "Academic Profile & Degree Audit", "profile.curriculum": "Your curriculum",
  "profile.eyebrow": "Your profile",
  "profile.heroTitle": "Save your program and curriculum term",
  "profile.heroBody": "The degree audit only ever uses the official requirements for the program and term you save here — both are required for an accurate result.",
  "profile.major": "Major (program)", "profile.selectMajor": "Select major…",
  "profile.term": "Curriculum (admit) term", "profile.selectTerm": "Select curriculum term…",
  "profile.degreeCode": "Degree code: {code}", "profile.year": "Current academic year",
  "profile.yearUnknown": "Not specified (use conservative planning)", "profile.save": "Save profile",
  "profile.saved": "Profile saved.", "profile.pickFirst": "Pick your major and curriculum term first.",
  "profile.loadFailed": "Could not load curricula.", "profile.saveFailed": "Save failed.",
  "profile.contract": "Your curriculum term is your graduation contract; the audit uses the official requirements for exactly this program and term.",
  "profile.audit": "Degree audit", "profile.runAudit": "Run audit",
  "profile.auditFailed": "Audit failed — save your profile first.", "profile.auditHelpBefore": "Save your profile, add your completed courses on the",
  "profile.auditHelpLink": "Course History", "profile.auditHelpAfter": "page, then run the audit.",
  "profile.suCredits": "/ {total} SU credits", "profile.category": "Category", "profile.done": "Done",
  "profile.need": "Need", "profile.remaining": "Remaining", "profile.left": "{count} left",
  "profile.missing": "Missing required:", "profile.reliability": "Reliability: {value} · computed deterministically from official requirements.",
  "courses.title": "Course History", "courses.completed": "Completed courses", "courses.savedCount": "{count} saved",
  "courses.eyebrow": "Your course history",
  "courses.heroTitle": "Mark the courses you've completed",
  "courses.heroBody": "Upload your transcript for automatic entry, or search the catalog.",
  "courses.emptyTitle": "No courses added yet",
  "courses.empty": "Search the catalog, select the courses you completed, and save; they will appear here and be used in your degree audit.",
  "courses.countNote": "Only completed courses count toward graduation. The degree audit reads this list.",
  "courses.gpa": "GPA",
  "courses.transcriptTitle": "Import from transcript",
  "courses.transcriptBrowse": "Choose transcript PDF",
  "courses.transcriptParsing": "Processing transcript…",
  "courses.transcriptImported": "{count} courses processed from your transcript. GPA: {gpa}",
  "courses.transcriptUnmatched": "Courses not found in the catalog: {codes}",
  "courses.transcriptFailed": "Could not process this transcript.",
  "courses.grade": "Grade",
  "courses.gradeNone": "No grade",
  "courses.clearAll": "Clear all",
  "courses.clearAllConfirmTitle": "Clear all courses?",
  "courses.clearAllConfirmBody": "All {count} saved courses will be removed from this list. This can't be undone.",
  "courses.clearAllConfirmAction": "Yes, clear all",
  "courses.removeCourse": "Remove course",
  "courses.add": "Add courses", "courses.search": "Search CS 300, MATH 101…", "courses.loading": "Loading courses",
  "courses.none": "No courses found", "courses.saveCount": "Save {count} courses",
  "courses.catalogFailed": "Could not load the course catalog.", "courses.historyFailed": "Could not load your saved course history.",
  "courses.savedToast": "Saved {count} completed courses.", "courses.saveFailed": "Could not save your course history.",
  "courses.documents": "Course documents", "courses.browse": "Click to browse", "courses.removeFile": "Remove file",
  "courses.indexing": "Indexing…", "courses.upload": "Upload to adviSU",
  "courses.uploaded": "Uploaded {files} files — {chunks} chunks indexed", "courses.skipped": "Skipped: {files}",
  "courses.uploadFailed": "Upload failed.",
  "schedule.title": "Course Schedule", "schedule.reference": "Designed with SUchedule (aburakayaz) as a reference",
  "schedule.term": "term {term}", "schedule.pick": "Select course and section", "schedule.officialSuffix": "official SUIS data",
  "schedule.seasonFall": "Fall", "schedule.seasonSpring": "Spring", "schedule.seasonSummer": "Summer",
  "schedule.courseCount": "{count} courses", "schedule.search": "Search by course code, title, instructor, or CRN",
  "schedule.clearSearch": "Clear search", "schedule.filterDay": "Filter by day", "schedule.byDay": "By day",
  "schedule.loading": "Loading courses", "schedule.loadFailed": "Could not reach the course list.",
  "schedule.localSafe": "Your current schedule is safe on this device.",
  "schedule.noResults": "No course matches the search or day filter.", "schedule.selected": "{count} selected",
  "schedule.alreadySelected": "This section is already in your schedule.",
  "schedule.moreHint": "Enter a course code or CRN for more precise results.", "schedule.week": "Weekly view",
  "schedule.weekHint": "Select a course to change its section; × removes linked components together.",
  "schedule.downloadExcel": "Download Excel", "schedule.removeBundle": "Remove {course} and linked sections",
  "schedule.time": "Time", "schedule.conflicting": "Conflict", "schedule.conflicts": "{count} conflicts",
  "schedule.emptyTitle": "Start building your schedule", "schedule.emptyBody": "Select a course and section on the left or import a schedule created by the chatbot.",
  "schedule.noClass": "No classes", "schedule.saving": "Saving", "schedule.offline": "Saved on this device",
  "schedule.noTime": "Time not announced", "schedule.sectionLoadFailed": "Could not load section options for {course}.",
  "schedule.primaryUpdated": "Updated the course section for {course}.",
  "schedule.incompatibleRemoved": "Updated {course}; removed an incompatible linked section.",
  "schedule.added": "Added {course} to the schedule.", "schedule.bundleAdded": "Added {course} with its linked {component}.",
  "schedule.secondaryUpdated": "Updated the {component} section for {course}.",
  "schedule.bundleRemoved": "Removed {course} and its linked sections.", "schedule.removed": "Removed {course} from the schedule.",
  "schedule.copyFailed": "Could not copy CRNs to the clipboard.",
  "schedule.clearConfirmTitle": "Clear schedule",
  "schedule.clearConfirm": "Are you sure you want to remove every course from your schedule? This cannot be undone.",
  "schedule.cleared": "Course schedule cleared.",
  "schedule.dayMon": "Monday", "schedule.dayTue": "Tuesday", "schedule.dayWed": "Wednesday",
  "schedule.dayThu": "Thursday", "schedule.dayFri": "Friday", "schedule.dayMonShort": "Mon",
  "schedule.dayTueShort": "Tue", "schedule.dayWedShort": "Wed", "schedule.dayThuShort": "Thu",
  "schedule.dayFriShort": "Fri", "schedule.defaultTerm": "Fall 2026-2027", "schedule.defaultComponent": "Course",
  "policy.title": "Course review data policy", "policy.status": "This feature is currently disabled.",
  "policy.body": "If released, it will evaluate courses only—not professors or instructors.",
  "policy.point1": "Explicit consent is required for every submission.",
  "policy.point2": "Private WhatsApp and course-group messages are never imported.",
  "policy.point3": "Only difficulty, workload, learning value, organization, and overall satisfaction are rated.",
  "policy.point4": "Comments require moderation; personal and instructor names are filtered.",
  "policy.point5": "Statistics remain hidden until at least 10 approved reviews exist.",
  "policy.point6": "Small subgroups and raw identities are never displayed.", "policy.back": "Back to sign in",
  "review.title": "Rate your course", "review.courseCode": "Course code",
  "review.courseCodePlaceholder": "CS 201", "review.difficulty": "Difficulty",
  "review.workload": "Workload", "review.learningValue": "Learning value",
  "review.organization": "Organization", "review.satisfaction": "Overall satisfaction",
  "review.scoreLabel": "{dimension}: {score} / 5",
  "review.comment": "Course comment (optional; moderation required)",
  "review.commentPlaceholder": "Do not include names or contact details.",
  "review.consent": "I explicitly consent to processing my ratings at course level under the privacy threshold.",
  "review.courseOnly": "This form evaluates the course only; instructors and people cannot be rated.",
  "review.privacyLink": "Read the privacy policy", "review.submit": "Submit review",
  "review.submitting": "Submitting…", "review.signIn": "Sign in to submit a review.",
  "review.loadError": "Could not load the course-review policy.",
  "review.submitError": "The review could not be submitted.",
  "review.pending": "Your review is awaiting moderation.",
  "review.approved": "Your numeric course rating was accepted.",
  "review.rejected": "The review did not meet the privacy policy.",
  "review.aggregateTitle": "Course statistics", "review.aggregateLoading": "Loading statistics…",
  "review.aggregateSuppressed": "Statistics remain hidden until at least 10 approved reviews exist.",
  "review.aggregateError": "Statistics could not be loaded.",
  "review.reviewCount": "{count} approved reviews", "review.delete": "Delete my review",
  "review.deleting": "Deleting…", "review.deleted": "Your review was deleted.",
  "review.deleteError": "The review could not be deleted.",
  "export.courseCode": "Course Code", "export.courseName": "Course Name", "export.su": "SU Credits",
  "export.status": "Status", "export.total": "TOTAL (credit eligible)", "export.courseHistorySheet": "Course History",
  "export.field": "Field", "export.value": "Value", "export.program": "Program",
  "export.curriculumTerm": "Curriculum term", "export.completedSu": "Completed SU",
  "export.requiredSu": "Required SU", "export.remainingSu": "Remaining SU", "export.reliability": "Reliability",
  "export.summarySheet": "Summary", "export.categoriesSheet": "Categories",
  "export.missingCourse": "Missing Required Course", "export.missingSheet": "Missing Required",
  "export.type": "Type", "export.dayTime": "Day / Time", "export.location": "Location",
  "export.instructor": "Instructor", "export.weekSheet": "Weekly Schedule",
  "export.term": "Term", "export.completedEcts": "Completed ECTS",
  "export.requiredEcts": "Required ECTS", "export.remainingEcts": "Remaining ECTS",
  "help.button": "Help", "help.title": "How adviSU works",
  "help.tip1": "Ask in plain language — “Is CS 306 required?” works fine.",
  "help.tip2": "Save your major and curriculum term on Profile for a personal degree audit.",
  "help.tip3": "Mark completed courses on Course History; the audit reads that list.",
  "help.tip4": "Pick sections on Course Schedule — conflicts are flagged automatically.",
  "help.close": "Close",
};

export type TranslationKey = keyof typeof tr;
export const resources: Record<Locale, Record<TranslationKey, string>> = { tr, en };

export function getStoredLocale(): Locale {
  const stored = globalThis.localStorage?.getItem("advisu-locale");
  if (stored === "tr" || stored === "en") return stored;
  return globalThis.navigator?.language?.toLowerCase().startsWith("tr") ? "tr" : "en";
}

export function translate(
  locale: Locale,
  key: TranslationKey,
  values: Record<string, string | number> = {},
): string {
  return Object.entries(values).reduce(
    (message, [name, value]) => message.split(`{${name}}`).join(String(value)),
    resources[locale][key],
  );
}

export const localizedContent = {
  taglines: (locale: Locale) => [
    translate(locale, "login.tagline1"), translate(locale, "login.tagline2"), translate(locale, "login.tagline3"),
  ],
  sampleQuestions: (locale: Locale) => locale === "tr" ? [
    "Kabul dönemime göre CS 306 zorunlu mu, çekirdek ders mi?",
    "Kabul dönemime göre CS 303 zorunlu mu?",
    "Mezuniyet için kaç temel bilim kredim kaldı?",
    "Profilime göre mezuniyet şartlarımı özetle",
  ] : [
    "Is CS 306 required or core based on my admit term?",
    "Is CS 303 required based on my admit term?",
    "How many basic science credits do I have left to graduate?",
    "Summarise my graduation requirements based on my profile",
  ],
  starters: (locale: Locale) => locale === "tr" ? [
    ["Mezuniyet durumumu hesapla", "Mezuniyet durumumu hesapla"],
    ["Bu dönem hangi dersleri alayım?", "Bu dönem hangi dersleri alayım?"],
    ["Mezun olana kadar hangi dersleri almalıyım?", "Mezun olana kadar hangi dersleri almalıyım?"],
    ["Bu dönem GPA'mı ne kadar yükseltebilirim?", "Bu dönem GPA'mı ne kadar yükseltebilirim?"],
  ] : [
    ["Calculate my degree progress", "Calculate my degree progress"],
    ["Which courses should I take this term?", "Which courses should I take this term?"],
    ["What should I take until graduation?", "What should I take until graduation?"],
    ["How much could I raise my GPA this term?", "How much could I raise my GPA this term?"],
  ],
} as const;

export function localizedWeekDays(locale: Locale) {
  return [
    { code: "M" as const, short: translate(locale, "schedule.dayMonShort"), label: translate(locale, "schedule.dayMon") },
    { code: "T" as const, short: translate(locale, "schedule.dayTueShort"), label: translate(locale, "schedule.dayTue") },
    { code: "W" as const, short: translate(locale, "schedule.dayWedShort"), label: translate(locale, "schedule.dayWed") },
    { code: "R" as const, short: translate(locale, "schedule.dayThuShort"), label: translate(locale, "schedule.dayThu") },
    { code: "F" as const, short: translate(locale, "schedule.dayFriShort"), label: translate(locale, "schedule.dayFri") },
  ];
}
